### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Sick-Carlito** [Sick-Carlito/Bubble-Sort-Ruby#1]
We did a peer to peer code review on this simple bubble sort program in Ruby.

**Comment by ghost** [comment]
The algorithm behaves as expected: sorta is that the larger elements will “bubble” towards the end and the smaller elements will “bubble” towards the beginning in a loop until all elements are properly ordered

**Comment by Elijahscriptdev** [comment]
The algorithm works perfectly

**Comment by gagc056** [comment]
there is no issue with it, it works
